name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Change if you need a different version

      # 3. Install dependencies inside a virtual environment
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest black

      # 4. Run pytest (skip if no tests)
      - name: Run Pytest
        run: |
          source venv/bin/activate
          if compgen -G "tests/test_*.py" > /dev/null; then
            pytest
          else
            echo "No tests found, skipping pytest."
          fi

      # 5. Run black check
      - name: Check formatting with black
        run: |
          source venv/bin/activate
          black --check .
